import { useEffect, useMemo, useState } from "react";
import type { ChangeEvent } from "react";
import { api } from "../../lib/api";
import type { Engine, Job, Settings } from "../../lib/api";

const imageTypes = ["image/png", "image/jpeg", "image/webp"];
const audioTypes = ["audio/wav", "audio/mpeg", "audio/mp4", "audio/aac", "audio/flac", "audio/ogg", "audio/webm"];

function InputPreview({ file, kind, onRemove }: { file: File | null; kind: "image" | "audio"; onRemove: () => void }) {
  const url = useMemo(() => file ? URL.createObjectURL(file) : "", [file]);
  useEffect(() => () => { if (url) URL.revokeObjectURL(url); }, [url]);
  if (!file) return null;
  return <div className="preview">{kind === "image" ? <img src={url} alt="Portrait preview" /> : <audio controls src={url} />}<div><strong>{file.name}</strong><small>{(file.size / 1024 / 1024).toFixed(2)} MB</small></div><button className="quiet" onClick={onRemove}>Remove</button></div>;
}

function FileField({ accept, label, file, onChange, kind }: { accept: string; label: string; file: File | null; onChange: (file: File | null) => void; kind: "image" | "audio" }) {
  const select = (event: ChangeEvent<HTMLInputElement>) => onChange(event.target.files?.[0] ?? null);
  return <label className="dropzone"><input type="file" accept={accept} onChange={select} /><span>{label}</span><small>Choose a local file or drop it here</small><InputPreview file={file} kind={kind} onRemove={() => onChange(null)} /></label>;
}

export function CreatePage() {
  const [portrait, setPortrait] = useState<File | null>(null); const [audio, setAudio] = useState<File | null>(null); const [reference, setReference] = useState<File | null>(null);
  const [mode, setMode] = useState<"speech" | "clone">("speech"); const [script, setScript] = useState(""); const [preset, setPreset] = useState("balanced"); const [watermark, setWatermark] = useState(true); const [consent, setConsent] = useState(false);
  const [engines, setEngines] = useState<Engine[]>([]); const [checkingEngines, setCheckingEngines] = useState(true); const [job, setJob] = useState<Job | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; const load = () => api.get<Engine[]>("/engines").then(value => { if (active) { setEngines(value); setCheckingEngines(false); } }).catch(() => { if (active) { setCheckingEngines(false); setError("Backend is not available. Run scripts\\windows\\start.ps1."); } }); void load(); const timer = window.setInterval(load, 15000); return () => { active = false; window.clearInterval(timer); }; }, []);
  useEffect(() => { api.get<Settings>("/settings").then(value => { setPreset(value.default_preset); setWatermark(value.watermark_enabled); }).catch(() => undefined); }, []);
  useEffect(() => { if (!job || ["completed", "failed", "cancelled"].includes(job.state)) return; const timer = window.setInterval(() => { api.get<Job>(`/jobs/${job.id}`).then(setJob).catch(() => setError("Could not refresh the running job.")); }, 1500); return () => window.clearInterval(timer); }, [job]);
  const sadTalkerReady = engines.some(engine => engine.engine_id === "sadtalker" && engine.installed && engine.models_ready);
  const chatterboxReady = engines.some(engine => engine.engine_id === "chatterbox" && engine.installed && engine.models_ready);
  const ready = sadTalkerReady && (mode === "speech" || chatterboxReady); const fileValid = portrait && (mode === "speech" ? audio : reference && script.trim());
  async function create() { let next: Job | null = null; try { setError(""); next = await api.post<Job>("/jobs", { workflow: mode, preset, watermark }); const send = async (kind: string, file: File) => { const form = new FormData(); form.append("file", file); const response = await fetch(`/api/v1/jobs/${next!.id}/inputs/${kind}`, { method: "POST", body: form }); if (!response.ok) throw new Error(await response.text()); }; await send("portrait", portrait!); await send(mode === "speech" ? "audio" : "reference", mode === "speech" ? audio! : reference!); setJob(await api.post<Job>(`/jobs/${next.id}/start`)); } catch { if (next) void api.delete(`/jobs/${next.id}`).catch(() => undefined); setError("AvatarKit could not validate or queue these local files. Check Diagnostics and media guidance."); } }
  return <main className="create"><header><p className="eyebrow">LOCAL AVATAR STUDIO / V0.1</p><h1>Create a consented talking avatar.</h1><p className="intro">Your files remain on this computer. AvatarKit never uploads portraits or recordings.</p></header>
    {checkingEngines && <aside className="warning">Checking local engines…</aside>}{!checkingEngines && !ready && <aside className="warning">{mode === "speech" ? "SadTalker is not ready. Check Diagnostics before generation." : "SadTalker and Chatterbox must both be ready for cloned speech."}</aside>}{error && <aside className="error">{error}</aside>}
    <section><div className="step">01 / Portrait</div><h2>Start with one clear portrait.</h2><FileField accept=".png,.jpg,.jpeg,.webp" label="Drop a PNG, JPG, or WEBP" file={portrait} onChange={f => setPortrait(f && imageTypes.includes(f.type) ? f : null)} kind="image" /><p className="hint">Front-facing, evenly lit, unobstructed face; use only one visible person.</p></section>
    <section><div className="step">02 / Voice mode</div><div className="tabs"><button className={mode === "speech" ? "active" : ""} onClick={() => setMode("speech")}>Existing speech</button><button className={mode === "clone" ? "active" : ""} onClick={() => setMode("clone")}>Clone from text</button></div>{mode === "speech" ? <><h2>Use the words the avatar should speak.</h2><FileField accept="audio/*" label="Drop speech audio" file={audio} onChange={f => setAudio(f && audioTypes.includes(f.type) ? f : null)} kind="audio" /></> : <><label className="script"><span>Script <b>{script.length} characters</b></span><textarea value={script} onChange={e => setScript(e.target.value)} placeholder="Write what your avatar should say…" /></label><FileField accept="audio/*" label="Drop a clean voice reference" file={reference} onChange={f => setReference(f && audioTypes.includes(f.type) ? f : null)} kind="audio" /><p className="hint">Use 10–30 seconds of one person speaking in a quiet room. English is available with the v0.1 engine.</p></>}</section>
    <section><div className="step">03 / Generation</div><div className="presets">{[["fast", "Fast test", "Short validation clips"], ["balanced", "Balanced", "Default for 8 GB VRAM"], ["best", "Best quality", "Takes longer"]].map(([id, title, detail]) => <button key={id} className={preset === id ? "preset selected" : "preset"} onClick={() => setPreset(id)}><strong>{title}</strong><small>{detail}</small></button>)}</div><label className="check"><input type="checkbox" checked={watermark} onChange={e => setWatermark(e.target.checked)} /> Add visible AI-generated watermark</label></section>
    <section><div className="step">04 / Consent</div><label className="check"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} /> I confirm that I own or have permission to use this face and voice.</label><p className="hint">Only create avatars of yourself or people who have explicitly consented.</p></section>
    <button className="generate" disabled={!fileValid || !consent || !ready || (job != null && !["completed", "failed", "cancelled"].includes(job.state))} onClick={create}>Generate locally</button>{job && <aside className={`job ${job.state === "failed" ? "error" : ""}`}><div><b>Job {job.id}</b><span>{job.phase}</span>{job.error_message && <small>{job.error_message}</small>}</div>{!["completed", "failed", "cancelled"].includes(job.state) && <button className="quiet" onClick={async () => setJob(await api.post<Job>(`/jobs/${job.id}/cancel`))}>Cancel</button>}</aside>}{job?.state === "completed" && <section className="result"><h2>Your avatar is ready</h2><video controls src={`/api/v1/jobs/${job.id}/output`} /><a href={`/api/v1/jobs/${job.id}/output`} download>Download MP4</a></section>}</main>;
}
